### ISSUE TITLE
Add "How to write migrations" topic on Readme

### ISSUE THREAD

**Issue by BernardoSilva** [mongrate/mongrate#12]
- [ ] Explain how to write migration `up`
- [ ] Explain how to write migration `down`
- [ ] Add migration examples or link to existing examples/tests.

**Comment by evillemez** [comment]
+1 - I'm going to need a proper mongo migration solution very soon, would love to give this a shot.

**Comment by amyboyd** [comment]
Hi @evillemez - @BernardoSilva and I will try get onto that this weekend! In the mean time, there are some examples in https://github.com/mongrate/mongrate/tree/master/resources/examples

**Comment by evillemez** [comment]
Ah, cool, will check it out, thanks for the pointer!

**Comment by amyboyd** [comment]
@evillemez Cool, if the examples need more detail, or there's anything you're unsure about, let me know and I'll do my best to help.

I've spent today writing some documentation, now available at http://mongrate.com/docs

I thought the installation process looked a bit daunting, so it is much simpler now, and can be done with just a `wget` (like Composer!).

**Comment by evillemez** [comment]
Ah, that's great, thanks!

Sorry for the delay, I'm working alone on a big project at the moment, so I'm kinda flitting to whichever fire is burning the hottest.  Haven't had a chance to actually try it out yet, but as soon as I do I'll let you know.  

The examples are good though, I like the approach to for providing tests for the migrations, I need that badly for peace of mind.

**Comment by amyboyd** [comment]
Closed by http://mongrate.com/docs/writing-migrations
