### ISSUE TITLE
Ensure up-all command apply migrations by date.

### ISSUE THREAD

**Issue by BernardoSilva** [mongrate/mongrate#39]
When migrations are written like suggested ending with `date` on migration name the command `up-all` should apply the pending migrations from the `oldest` to the `recent` one.

e.g.

* MyMigration_20150914
* MyMigration_20150915
* MyMigration_20150905

The migration up order should be:

1. MyMigration_20150905
2. MyMigration_20150914
3. MyMigration_20150915

**Comment by amyboyd** [comment]
This goes against one of the project's original goals:

`To be non-linear, so migrations can be applied in any order and at any time.`

**Comment by amyboyd** [comment]
If we want this, it should be part of Autobot IMO. Closing for now as this isn't relevant to Mongrate.
