### ISSUE TITLE
Version Lock for Mongrate

### ISSUE THREAD

**Issue by HadesArchitect** [mongrate/mongrate#50]
v1.7.0 of mongrate (as far as current dev-master) requires old doctrine/mongodb -  1.1.*, which is outdated, actual version is 1.3.

The problem is, doctrine/mongodb:v1.1.* requires previous, also outdated version of PHP extension Mongo. As a result, **it's impossible to install the mongrate** on a machine with mongo extension v1.6.*

> $ php --ri mongo
> MongoDB Support => enabled
> Version => 1.6.13

Is it possible to update the requirement to ~1.0 for example?

**Comment by amyboyd** [comment]
This has been a pain-point in the past. Ubuntu 14.04 (common for PHP stacks) ships with mongo extension 1.4. I think it's the same for CentOS.

![image](https://cloud.githubusercontent.com/assets/398210/16308651/c6438dda-395d-11e6-8b07-02d4fa339bcf.png)

If there's a Doctrine version that works with mongo extension 1.4, 1.5 and 1.6, then yes it would be great to change to that.

**Comment by amyboyd** [comment]
From `doctrine/mongodb` composer.json:

1.3:

```
        "php": "^5.5 || ^7.0",
        "ext-mongo": "^1.5",
```

1.2:

```
        "php": ">=5.3.2",
        "ext-mongo": "^1.2.12",
```

1.1:

```
        "php": ">=5.3.2",
        "ext-mongo": ">=1.2.12,<1.6-dev",
```

**Comment by amyboyd** [comment]
@HadesArchitect Can you try with this please? https://github.com/mongrate/mongrate/pull/51

**Comment by HadesArchitect** [comment]
Works well!

```
developer@df1037df46d0$ php --ri mongo | grep -i version
Version => 1.6.13

developer@df1037df46d0$ composer show amyboyd/mongrate | grep -i version
versions : * dev-50-doctrine-version
source : https://github.com/amyboyd/mongrate/tree/50-doctrine-version
```

The question is, how it will work for old installations?

**Comment by amyboyd** [comment]
I'm going to test this on PHP 5.5 with driver 1.4/1.5, and PHP 5.6 with driver 1.5/1.6. Will be home from work in about 30 minutes to start testing. If it's all OK then I'll merge.

Issues like these make me really appreciate Go and it's single binary distribution!

**Comment by HadesArchitect** [comment]
Cool, thanks
